version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: server:latest
    env_file:
      - .env
    expose:
      - 5000
    networks:
      - server-network

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./NGINX/nginx.conf:/etc/nginx/nginx.conf:ro   # 👈 make sure this is in a list format
    depends_on:
      - server
    environment:
      NGINX_HOST: "localhost"
      NGINX_PORT: 80
    restart: always
    networks:
      - server-network


networks:
  server-network:
    driver: bridge
